not reduced sample, but reddit plotting model idea
NOTE IT DOESNT ACTUALLY WORK, csv file part expects 
AnalysisException: 'CSV data source does not support array<string> data type.;'